### ISSUE TITLE
Roamit put each received file into separate folder

### ISSUE THREAD

**Issue by Foxard** [MahdiGhiasi/Roamit#22]
Upon receiving files Roamit makes separate folders for each of them within main receiving folder set in settings. And puts received files into these folders. Folders names are the same as file names. There is no such setting in Settings pane, mine Roamit set to "Don't group", but this is ignored. The issue appeared with the latest app upgrade to 3.2.2.0 (Windows 10, build 1809).

**Comment by MahdiGhiasi** [comment]
Thanks. I was able to reproduce this. Will look into it.

**Comment by MahdiGhiasi** [comment]
This has been fixed [in this commit](https://github.com/MahdiGhiasi/Roamit/commit/a6dd284e819341a26f33ee29ff56b790c2d67b33) and will be available in the next update.
