### ISSUE TITLE
Windows and Android versions can't find other devices and both throw errors

### ISSUE THREAD

**Issue by Kenya-West** [MahdiGhiasi/Roamit#23]
Here are the errors they throw, then close themselves:

Windows:
![2018-12-06_12-07-48](https://user-images.githubusercontent.com/12271104/49558846-dd940c80-f94f-11e8-9f21-783ab950d1ae.png)

Android:
![screenshot_2018-12-06-12-08-27-526_com miui bugreport](https://user-images.githubusercontent.com/12271104/49558847-de2ca300-f94f-11e8-99f4-9aa29560284a.png)

What happened with Roamit, again?

**Comment by Kenya-West** [comment]
> check if you can visit https://roamit.ghiasi.net via your browser normally and let me know the result.

Aha! I figured out what is going on! Your server (specifically, its IP address) **is banned** by russian authorities - Russian Federal Communications Watch (Roskomnadzor).

It is confirmed by also russian Telegram channel and automated system initiative called **Usher2**, here is the proof:
![roamit_ip_block_check_1](https://user-images.githubusercontent.com/12271104/49585680-620f7b00-f9a2-11e8-96bf-75dc0be8681b.jpg)

You can check it yourself [there](http://t.me/rkn_block_check_bot) (if you master russian language first hmm).

I guess you are using [DigitalOcean IP range](https://whatismyipaddress.com/ip/167.99.151.146) which is almost completely banned in Russia. So, russian users cannot use your app at all.

Could you please move the domain and website to another IP address space hosted by other provider?
Microsoft Azure for example is not banned in Russia but AWS banned partly.

P. S. Of course, russian users do not make such significant percent of userbase as american/chinese/indian/europe, but I think, we can find a solution for Russia.

P. P. S. Microsoft's Feedback Hub was also banned at one time, but they moved to another IP range by request of russian Insiders.

**Comment by MahdiGhiasi** [comment]
@Kenya-West 

Ah, I see. Thanks for that!

Roamit's main IP address is not on DigitalOcean, but I've experienced some issues on that server, so I **temporarily** moved Roamit to a new server on DigitalOcean.

The issues on our main server will hopefully get resolved in a few days, and I'll move back Roamit to it. So Roamit will be available for Russian users again soon. 😊

**Comment by Kenya-West** [comment]
@MahdiGhiasi thanks for information! Waiting until it will be resolved.

**Comment by MahdiGhiasi** [comment]
@Kenya-West I've moved the server back to it's original location. Can you confirm that it's working now in your region?

**Comment by Kenya-West** [comment]
> I've moved the server back to it's original location. Can you confirm that it's working now in your region?

Yep, all apps both on Android and Windows now work correctly. Thank you for resolving the issue!

Proof (green check mark means that IP is unlocked for Russian Federation):
![image](https://user-images.githubusercontent.com/12271104/50010653-64ef1900-fffd-11e8-807d-3eec9da4dc64.png)

**Comment by MahdiGhiasi** [comment]
@Kenya-West Hey, can you check again to see if Roamit is accessible from Russia? I've activated Cloudflare for the domain, and I was wondering if that changes anything for Russian users.

Thanks.

**Comment by Kenya-West** [comment]
@MahdiGhiasi everything is working fine.

**Comment by MahdiGhiasi** [comment]
@Kenya-West Happy to hear that. Thanks.
