### ISSUE TITLE
Opportuntity for feedback using Project Rome

### ISSUE THREAD

**Issue by cmknox** [MahdiGhiasi/Roamit#27]
@MahdiGhiasi I am from the Project Rome team at Microsoft.  I would love to chat with you about using the platform and get your feedback.  Please let me know if you are interested.  I can be reached at 'carmenf@microsoft.com'.  

@MahdiGhiasi I saw no other contact information, so I'm trying this approach.

**Comment by MahdiGhiasi** [comment]
@cmknox I will be glad to have a chat with you about this, and I just sent you an email. 

Thank you.
