### ISSUE TITLE
FailedToRegister error - Can't sign in

### ISSUE THREAD

**Issue by Santi3598** [MahdiGhiasi/Roamit#33]
I downloaded the app for my Android device, and for my PC. When trying to sign in on my phone, I get this "FailedToRegister" error, and on my PC it just never ends loading. My internet is working fine.

**Comment by This-Person** [comment]
Same issue here. Everything was working fine until very recently. Clearing app data/reinstalling etc doesn't help on Android. 

"FailedToRegister Please try again later." pops up in a grey box.

**Comment by MahdiGhiasi** [comment]
Sorry for the inconvenience. The issue is now resolved and Roamit should work fine again.

**Comment by This-Person** [comment]
Can confirm that it's working again. I signed in first time no problem. Thanks a lot!

**Comment by Santi3598** [comment]
I second that, it is working now. Thanks!
