### ISSUE TITLE
Option to enable notification

### ISSUE THREAD

**Issue by Kenya-West** [MahdiGhiasi/Roamit#5]
After reinstalling the app on Android I see no permanent notification where I can copy Universal Clipboard value by tap. How to enable that notification? I don't what to mirror clipboard automatically, I wish to copy clipboard manually from Android's action center when I want to.

**Comment by MahdiGhiasi** [comment]
In the Android app, make sure "Receive Universal clipboard on this device" option is turned **on**, and "Reflect clipboard changes automatically to this device" is turned **off**.

If you don't see these options, make sure Roamit on your PC is set up correctly, meaning Universal clipboard is enabled and the icon is there in system tray, and also under "Manage universal clipboard for my other devices", your Android device  is checked.

The options on your Android device about being automatic or notification center will become visible after you receive the first piece of Universal clipboard on your device.

**Comment by Kenya-West** [comment]
Everything is correct, as I see...
![2018-01-21_13-28-29](https://user-images.githubusercontent.com/12271104/35190847-407b6b00-feaf-11e7-8893-19bc6a148ba5.jpg)
![screenshot_2018-01-21-13-29-10-406_com ghiasi roamitapp](https://user-images.githubusercontent.com/12271104/35190848-40a58afc-feaf-11e7-8dea-fa704c7ba357.png)

Sorry for big screenshots, can't force them to get small.

**Comment by AkazaDorian** [comment]
@MahdiGhiasi I think what he wants is disabling the popup toast when android receives a clipboard update

**Comment by Kenya-West** [comment]
You can probably close the issue because notification has been appeared with one of the latest updates of the app.

![image](https://user-images.githubusercontent.com/12271104/46323916-af324200-c62b-11e8-8840-85e344fb07f6.png)

**Comment by MahdiGhiasi** [comment]
@Kenya-West Glad it finally worked for you. Thanks for the update.
